#!/usr/bin/env python3
"""build_food_index.py — emit a slim, bundle-friendly food search index.

Reads the full bilingual food database (src/data/food_db.json) and writes
src/data/food_index.json containing only the fields the client-side search
and the nutrition engine's evaluateFoodForProfile() actually need:

    id, name_ar, name_en, category, calories, portion_grams,
    serving_desc_ar, serving_desc_en, protein_g, carbs_g, fat_g,
    sugar_g, sodium_mg, tags

Run from the repo root:  python scripts/build_food_index.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "data" / "food_db.json"
OUT = ROOT / "src" / "data" / "food_index.json"

KEEP = (
    "id", "name_ar", "name_en", "category",
    "calories", "portion_grams",
    "serving_desc_ar", "serving_desc_en",
    "protein_g", "carbs_g", "fat_g",
    "sugar_g", "sodium_mg",
    "tags",
)


def main() -> None:
    db = json.loads(SRC.read_text(encoding="utf-8"))
    items = db["items"] if isinstance(db, dict) else db

    slim = []
    for it in items:
        row = {}
        for k in KEEP:
            v = it.get(k)
            if v is None:
                continue
            # Quantize floats: calories/sodium to ints, macros to 1 decimal.
            if isinstance(v, float):
                v = round(v) if k in ("calories", "sodium_mg") else round(v, 1)
            row[k] = v
        if not row.get("id") or not row.get("name_ar"):
            continue
        slim.append(row)

    payload = {
        "_meta": {
            "count": len(slim),
            "source": "food_db.json",
            "note": "Slim search index generated by scripts/build_food_index.py — do not edit by hand.",
        },
        "items": slim,
    }
    OUT.write_text(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    size_kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT} — {len(slim)} items, {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
